[package]
name = "conversational_agent_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
aleph-alpha-client = "0.7.0"
# todo: install  these packages.
qdrant-client = "1.4.0"

